apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: vishnupriya68/sample1:kubeimage1
          ports:
            - containerPort: 5000
